apiVersion: v1
kind: Service
metadata:
  name: play-poc-service
  labels:
    app: play-poc
spec:
  type: NodePort
  ports:
  - name: http-port
    port: 9000
  selector:
    app: play-poc
---
apiVersion: v1
kind: Service
metadata:
    name: play-poc-discovery-service
    labels:
      app: play-poc
spec:
  clusterIP: None
  ports:
  - name: cluster-port
    port: 2552
  selector:
    app: play-poc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: play-poc-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: play-poc
    spec:
      containers:
      - name: play-poc-container
        image: play-poc:1.0-SNAPSHOT
        ports:
        - containerPort: 2552
        - containerPort: 9000
        - containerPort: 9999
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 1
