apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: play-poc-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: play-poc
    spec:
      containers:
      - name: play-poc-container
        image: play-poc:1.0-SNAPSHOT
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: play-poc-secret
              key: secret
        ports:
        - containerPort: 2552
        - containerPort: 9000
        - containerPort: 9999
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "PID=`pidof java` && kill -SIGTERM $PID && while ps -p $PID > /dev/null; do sleep 5; done;"]
