apiVersion: v1
kind: Service
metadata:
  name: play-poc-service
  labels:
    app: play-poc
spec:
  type: NodePort
  ports:
  - name: http-port
    port: 9000
  selector:
    app: play-poc
---
apiVersion: v1
kind: Service
metadata:
    name: play-poc-discovery-service
    labels:
      app: play-poc
spec:
  clusterIP: None
  ports:
  - name: cluster-port
    port: 2552
  selector:
    app: play-poc
